Document xinitrc replacement flow for running Window Maker on X11

diff --git a/WindowMaker/Makefile.am b/WindowMaker/Makefile.am
--- a/WindowMaker/Makefile.am
+++ b/WindowMaker/Makefile.am
@@ -4,9 +4,13 @@ prefsdatadir = $(pkgdatadir)
 
 wpexecbindir = @wprefs_bindir@
 
+compositordir = $(pkgdatadir)/Compositors
+compositor_DATA = Compositors/picom.conf \
+        Compositors/compton.conf
+
 # menus which need generated to have correct path to WPrefs or data directory
 GENERATED_MENUS =\
-	appearance.menu\
+        appearance.menu\
 	appearance.menu.fy\
 	appearance.menu.nl\
 	appearance.menu.sr\
@@ -81,10 +85,22 @@ nodist_prefsdata_DATA = $(GENERATED_MENUS)
 xsessionsdir = @datadir@/xsessions
 xsessions_DATA = wmaker.desktop
 
-EXTRA_DIST = $(addsuffix .in, $(GENERATED_MENUS)) wmaker.desktop
+EXTRA_DIST = $(addsuffix .in, $(GENERATED_MENUS)) wmaker.desktop \
+        Compositors/picom.conf \
+        Compositors/compton.conf
 
 CLEANFILES = $(GENERATED_MENUS)
 
 $(GENERATED_MENUS):
 	$(AM_V_GEN)sed -e "s:#wprefs#:$(wpexecbindir)/WPrefs:" \
 		-e "s:#wmdatadir#:$(pkgdatadir):" $(srcdir)/$@.in > $@
+
+installcheck-local:
+	@test -f "$(DESTDIR)$(compositordir)/picom.conf" || { \
+		echo "installcheck: missing $(compositordir)/picom.conf" >&2; \
+		exit 1; \
+	}
+	@test -f "$(DESTDIR)$(compositordir)/compton.conf" || { \
+		echo "installcheck: missing $(compositordir)/compton.conf" >&2; \
+		exit 1; \
+	}
